 USE DB_COM2034

--BÀI 1:

DECLARE @BANG_TAM TABLE(
MA_SP VARCHAR(10),
TEN_SP VARCHAR(50),
TEN_DSP VARCHAR(50),
TEN_NSX VARCHAR(50),
TEN_MS NVARCHAR(50),
NAM_BH INT,
SL_TON INT,
GIA_NHAP DECIMAL(20,0) DEFAULT 0,
GIA_BAN DECIMAL(20,0) DEFAULT 0
)
INSERT INTO @BANG_TAM
SELECT SP.Ma, SP.Ten, DSP.Ten,NSX.Ten, MS.Ten, CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan
FROM SanPham SP JOIN ChiTietSP CTSP ON SP.Id = CTSP.IdSP
JOIN DongSP DSP ON DSP.Id = CTSP.IdDongSP
JOIN MauSac MS ON MS.Id = CTSP.IdMauSac
JOIN NSX ON NSX.Id = CTSP.IdNsx 
SELECT * FROM @BANG_TAM

DECLARE @SL_SP INT
SELECT @SL_SP = COUNT(MA_SP) FROM @BANG_TAM
IF @SL_SP > 10
	PRINT N'SẢN PHẨM TÌM THẤY CÓ TRÊN 10 SẢN PHẨM'
ELSE 
	PRINT N'KHÔNG TÌM THẤY SẢN PHẨM NÀO'

--BÀI 2: 

DECLARE @BAI2 TABLE(
MA_SP VARCHAR(10),
TEN_SP VARCHAR(50),
TEN_DSP VARCHAR(50),
TEN_NSX VARCHAR(50),
TEN_MS NVARCHAR(50),
NAM_BH INT,
SL_TON INT,
GIA_NHAP DECIMAL(20,0) DEFAULT 0,
GIA_BAN DECIMAL(20,0) DEFAULT 0,
SL_BAN INT,
TONG_TIEN_BAN DECIMAL(20,0) DEFAULT 0,
TONG_TIEN_NHAP  DECIMAL(20,0) DEFAULT 0
)
INSERT INTO @BAI2
SELECT  SP.Ma,SP.Ten, DSP.Ten,NSX.Ten, MS.Ten, CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan,SUM(HDCT.SoLuong) ,
SUM(HDCT.DonGia*HDCT.SoLuong),SUM(CTSP.GiaNhap * HDCT.SoLuong) 
FROM SanPham SP 
JOIN ChiTietSP CTSP ON SP.Id = CTSP.IdSP
JOIN DongSP DSP ON DSP.Id = CTSP.IdDongSP
JOIN MauSac MS ON MS.Id = CTSP.IdMauSac
JOIN NSX ON NSX.Id = CTSP.IdNsx 
JOIN HoaDonChiTiet HDCT ON HDCT.IdChiTietSP = CTSP.Id
GROUP BY SP.Ma,SP.Ten, DSP.Ten,NSX.Ten, MS.Ten, CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan
SELECT * FROM @BAI2
DECLARE @TONGTEN  DECIMAL(20,0)
SET @TONGTEN = (SELECT SUM(A.TONG_TIEN_BAN) FROM @BAI2 A)
PRINT N'TỔNG TIỀN ĐÃ BÁN: '+ CONVERT (NVARCHAR(50),@TONGTEN)

-------------
--BAI 4

SELECT TOP 10
SP.Ma, SP.Ten, DSP.Ten, NSX.Ten, MS.Ten,CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan, 
SUM(HDCT.SoLuong) AS N'SỐ LƯỢNG ĐÃ BÁN RA', SUM(HDCT.SoLuong * HDCT.DonGia) AS N'TỔNG TIỀN BÁN RA' 
FROM SanPham SP JOIN ChiTietSP CTSP ON SP.Id = CTSP.IdSP
			 JOIN DongSP DSP ON CTSP.IdDongSP = DSP.Id
			 JOIN NSX ON NSX.Id = CTSP.Id
			 JOIN MauSac MS ON MS.Id = CTSP.Id
			 JOIN HoaDonChiTiet HDCT ON HDCT.IdChiTietSP = CTSP.Id
			 JOIN HoaDon HD ON HD.Id = HDCT.IdHoaDon
WHERE MONTH(HD.NgayThanhToan) >=1 AND MONTH(HD.NgayThanhToan) <=4
GROUP BY SP.Ma, SP.Ten, DSP.Ten, NSX.Ten, MS.Ten,CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan
HAVING SUM(HDCT.SoLuong) >30
ORDER BY SUM(HDCT.SoLuong) DESC
IF @@ROWCOUNT <=0
	BEGIN
		PRINT N'KHÔNG CÓ SẢN PHẨM NÀO THỎA MÃN ĐK TRÊN TRONG Q1'
 	END
	
ELSE
 	BEGIN
	 	PRINT N'SẢN PHẨM THỎA MÃN ĐK TRÊN'
 	END


/*SELECT SP.Ma, SP.Ten, DSP.Ten, NSX.Ten, MS.Ten,CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan,sum(HDCT.SoLuong)
FROM SanPham SP JOIN ChiTietSP CTSP ON SP.Id = CTSP.IdSP
			 JOIN DongSP DSP ON CTSP.IdDongSP = DSP.Id
			 JOIN NSX ON NSX.Id = CTSP.Id
			 JOIN MauSac MS ON MS.Id = CTSP.Id
			 JOIN HoaDonChiTiet HDCT ON HDCT.IdChiTietSP = CTSP.Id
			 JOIN HoaDon HD ON HD.Id = HDCT.IdHoaDon
WHERE MONTH(HD.NgayThanhToan) >=1 AND MONTH(HD.NgayThanhToan) <=4
GROUP BY SP.Ma, SP.Ten, DSP.Ten, NSX.Ten, MS.Ten,CTSP.NamBH, CTSP.SoLuongTon,CTSP.GiaNhap, CTSP.GiaBan
HAVING sum(HDCT.SoLuong) >1 
*/

--BAI 3
DECLARE @BANG1 TABLE (
MA_CH NVARCHAR(5),
TONG_NV INT
)
INSERT INTO @BANG1 
SELECT A.Ma,SUM(A.SL) FROM (SELECT CH.Ma,COUNT(NV.Id) AS 'SL' FROM CuaHang CH JOIN NhanVien NV ON NV.IdCH = CH.Id
GROUP BY CH.Ma
) AS A
GROUP BY A.Ma
--SELECT * FROM @BANG1

DECLARE @BANG2 TABLE(
MA_CH NVARCHAR(5),
SL_NV_NAM INT
)
INSERT INTO @BANG2
SELECT CH.Ma, COUNT(NV.Id) AS [NV_NAM] FROM CuaHang CH JOIN NhanVien NV ON NV.IdCH = CH.Id WHERE NV.GioiTinh = N'NAM' GROUP BY CH.MA
INSERT INTO @BANG2
SELECT Ma,0 FROM CuaHang
--SELECT * FROM @BANG2 

DECLARE @BANG2_1 TABLE(
MA_CH NVARCHAR(5),
SL_NV_NAM INT
)
INSERT INTO @BANG2_1
SELECT R.MA_CH, SUM(R.SL_NV_NAM) FROM @BANG2 R GROUP BY R.MA_CH
--SELECT * FROM @BANG2_1

DECLARE @NHANVIEN TABLE(
MA_CH NVARCHAR(5),
SL_NV INT,
NV_NAM INT,
NV_NU INT
)
INSERT INTO @NHANVIEN
SELECT Y.MA_CH, Y.TONG_NV, X.SL_NV_NAM,Y.TONG_NV-X.SL_NV_NAM
FROM @BANG2_1 X  JOIN @BANG1 Y ON Y.MA_CH = X.MA_CH
--SELECT * FROM @NHANVIEN

DECLARE @BANG3 TABLE(
MA  NVARCHAR(5),
SL_CV INT
)
INSERT INTO @BANG3
 SELECT C.Ma,SUM(C.CV_NV) FROM(SELECT CH.Ma, COUNT(NV.Id) AS [CV_NV] FROM CuaHang CH JOIN NhanVien NV ON NV.IdCH = CH.Id
JOIN ChucVu CV ON CV.Id = NV.IdCV WHERE CV.Ten = N'Nhân Viên' GROUP BY CH.MA) AS C GROUP BY C.Ma
--SELECT * FROM @BANG3

DECLARE @BANG4 TABLE(
MA  NVARCHAR(5),
SL_CV_GD INT
)
INSERT INTO @BANG4
SELECT CH.Ma, COUNT(NV.Id) AS [CV_GD] FROM CuaHang CH JOIN NhanVien NV ON NV.IdCH = CH.Id
JOIN ChucVu CV ON CV.Id = NV.IdCV WHERE CV.Ten = N'Giám Đốc' GROUP BY CH.MA
INSERT INTO @BANG4
SELECT Ma,0 FROM CuaHang
--SELECT * FROM @BANG4

DECLARE @BANG4_1 TABLE(
MA  NVARCHAR(5),
SL_CV_GD INT
)
INSERT INTO @BANG4_1
SELECT MA, SUM(SL_CV_GD) FROM @BANG4  GROUP BY MA
--SELECT * FROM @BANG4_1
--------
DECLARE @BAI_3 TABLE (
	MA_CH VARCHAR(10),
	TEN_CH NVARCHAR(100),
	DIA_CHI NVARCHAR(100),
	THANH_PHO NVARCHAR(100),
	TEN1 NVARCHAR(100),
	TEN2 NVARCHAR(100),
	TONG_NV INT,
	SO_NV_NAM INT,
	SO_NV_NU INT,
	SO_CV_NV INT,
	SO_CV_GD INT
) 
INSERT INTO @BAI_3 
SELECT CH.Ma, CH.Ten,CH.DiaChi,CH.ThanhPho,
LEFT(ThanhPho,CHARINDEX(' ',ThanhPho)-1) ,
RIGHT(ThanhPho,LEN(ThanhPho) - CHARINDEX(' ',ThanhPho)),A.SL_NV,A.NV_NAM,A.NV_NU,B.SL_CV,C.SL_CV_GD
FROM 
CuaHang CH JOIN @NHANVIEN A ON A.MA_CH = CH.Ma
JOIN @BANG3 B ON B.MA = A.MA_CH
JOIN @BANG4_1 C ON C.MA= A.MA_CH
SELECT * FROM @BAI_3

DECLARE @TONG_SO_NV INT 
SELECT  @TONG_SO_NV = COUNT(NV.Id) FROM NhanVien NV JOIN CuaHang CH ON CH.Id = NV.IdCH
WHERE CH.ThanhPho = N'Hà Nội'  
PRINT N'TỔNG SỐ NHÂN VIÊN CỦA CÁC CỬA HÀNG TẠI HÀ NỘI: '+ CONVERT(VARCHAR(100),@TONG_SO_NV);
	
